From openjdk:17
Expose 8094
Add target/school_management_system-School-Version-1.0.jar school_management_system-School-Version-1.0.jar
ENTRYPOINT ["java","-jar","/school_management_system-School-Version-1.0.jar"]